### ISSUE TITLE
refactor: move sites out of astro to a single file

### ISSUE THREAD

**Issue by yjl9903** [liruifengv/astro-site-showcase-cn#36]
Now, we directly add component to add new sites.

<img width="779" alt="image" src="https://github.com/liruifengv/astro-site-showcase-cn/assets/30072175/dfc7f084-d7d3-40e5-a6ae-55df335f8c67">

I think it will be better to create a constant ts file to save all the sites information, for other generation usages, easy to refactor ui, adding other properties like github repo, and so on.

For example:

```astro
// constat.ts
export const sites = [
  // ...
]

// .astro
import { sites } from './constant'

---

{
  sites.map(site => (/** ... **/))
}
```

**Comment by liruifengv** [comment]
Nice suggestion! 

I'm considering using content collections to manage that in the future. 

But your suggestion is a good one, too. Would be happy to merge a PR for it if you’re interested?
